name: "Restore cache"
description: "Install and cache node_modules"

inputs:
  world:
    description: "Local world folder name"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Building ${{ inputs.world }}
      shell: bash
      working-directory: ./${{ inputs.world }}
      env:
        CLOSE_ON_SAVE: true
      run: |
        yarn
        yarn dev &

    - name: "Generate scene.json"
      shell: bash
      run: |
        node ./.github/actions/upload/dist/index.js

    - name: Publishing ${{ inputs.world }}
      shell: bash
      working-directory: ./${{ inputs.world }}
      run: |
        yarn upload
